language: python

python:
  - "2.7"

install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -q fabric==1.5.1"

before_script:
  - fab make_settings
  - mkdir -p $TRAVIS_BUILD_DIR/editorsnotes/static
  - fab collect_static
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - fab sync_database

script:
  - python manage.py test main api admin_custom
